    <table id="tableboard" class="display" width="100%" cellspacing="0">
		<thead>
			<tr>
				<th>ID</th>
				<th>Дата</th>
				<th>Заголовок</th>
				<th>Цена</th>
				<th>Автор</th>
				<th>Город</th>
				<th>Рубрика</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<th>ID</th>
				<th>Дата</th>
				<th>Заголовок</th>
				<th>Цена</th>
				<th>Автор</th>
				<th>Город</th>
				<th>Рубрика</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</tfoot>
    <tbody>